#!/run/dojo/bin/exec-suid -- /run/dojo/bin/python3 -I

print ("Desert CodeSprouts (Task 3)")

plaintext = open("/challenge/plaintext", "r").read()
user_plaintext = input('What is the plaintext? (all lowercase letters and no "!") \n')

if (plaintext == user_plaintext):
    flag = open("/flag", "r").read()
    print ("Correct!")
    print ("The flag is: ", fla)
else:
    print ("Sorry, that's wrong. Please try again!\n")
